### PR TITLE
tilde_enum_updated.py

### PR DESCRIPTION
**Pull request by darkmatter1505**
Bug Fix in performLookups function

### CODE REVIEW

**Comment by WebBreacher** [comment]
Instead of creating another file, can you modify the existing script with your changes and resubmit? Having 1 broken and 1 "updated" script in this small project will be confusing.

**Comment by darkmatter1505** [comment]
Done,


Edit the file and created pull request.

**Comment by WebBreacher** [comment]
Rejecting since a second pull request for just the modification to the original script was also submitted (and accepted).

**Comment by darkmatter1505** [comment]
Should I delete the repository I created?

**Comment by WebBreacher** [comment]
Yup. Feel free to since the master branch here now has your modifications.

**Pull request closed without merging**
